"""add_encrypted_tokens_to_integration

Revision ID: 2d12cdb45a52
Revises: 5293b6e8f1a1
Create Date: 2025-12-29 22:16:42.353390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d12cdb45a52'
down_revision: Union[str, Sequence[str], None] = '5293b6e8f1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True))
    op.add_column('integrations', sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=True))
    
    # --- Data Migration ---
    from app.core.security import encrypt_token
    
    # Use a connection to fetch and update
    connection = op.get_bind()
    
    # Fetch all integrations
    integrations = connection.execute(
        sa.text("SELECT id, access_token, refresh_token FROM integrations")
    ).fetchall()
    
    for row in integrations:
        integration_id = row[0]
        access_token = row[1]
        refresh_token = row[2]
        
        encrypted_access = encrypt_token(access_token) if access_token else None
        encrypted_refresh = encrypt_token(refresh_token) if refresh_token else None
        
        connection.execute(
            sa.text(
                "UPDATE integrations SET encrypted_access_token = :access, encrypted_refresh_token = :refresh WHERE id = :id"
            ),
            {"access": encrypted_access, "refresh": encrypted_refresh, "id": integration_id}
        )
    # --- End Data Migration ---

    op.add_column('users', sa.Column('target_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_note_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'api_key')
    op.drop_column('users', 'language')
    op.drop_column('users', 'has_onboarded')
    op.drop_column('users', 'oauth_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.drop_column('users', 'last_note_date')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'target_language')
    op.drop_column('integrations', 'encrypted_refresh_token')
    op.drop_column('integrations', 'encrypted_access_token')
    # ### end Alembic commands ###
