"""Initial_migration

Revision ID: 3da7c7a7eb0a
Revises: 
Create Date: 2025-12-25 00:33:16.023251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da7c7a7eb0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_embeddings',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.add_column('integrations', sa.Column('refresh_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    op.add_column('integrations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('integrations', 'access_token',
               existing_type=sa.VARCHAR(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               existing_nullable=False)
    op.add_column('notes', sa.Column('calendar_events', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('status', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('diarization', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('cluster_id', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('health_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('monthly_usage_seconds', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('billing_period', sa.String(), nullable=True))
    op.add_column('users', sa.Column('billing_cycle_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'billing_cycle_start')
    op.drop_column('users', 'billing_period')
    op.drop_column('users', 'monthly_usage_seconds')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'is_pro')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'first_name')
    op.drop_column('notes', 'health_data')
    op.drop_column('notes', 'cluster_id')
    op.drop_column('notes', 'diarization')
    op.drop_column('notes', 'status')
    op.drop_column('notes', 'calendar_events')
    op.alter_column('integrations', 'access_token',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('integrations', 'expires_at')
    op.drop_column('integrations', 'refresh_token')
    op.drop_table('note_embeddings')
    op.drop_table('integration_logs')
    # ### end Alembic commands ###
