"""add_dynamic_pricing_models

Revision ID: c737dc68d8b7
Revises: e1484e7bfcb3
Create Date: 2025-12-25 14:44:52.610589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c737dc68d8b7'
down_revision: Union[str, Sequence[str], None] = 'e1484e7bfcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('note_embeddings',
    # sa.Column('note_id', sa.String(), nullable=False),
    # sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    # sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    # sa.PrimaryKeyConstraint('note_id')
    # )
    
    # Seeding Logic
    op.execute("""
        INSERT INTO plans (id, name, price_monthly, price_yearly, features, is_active, created_at)
        VALUES 
        ('plan_free', 'free', 0, 0, '{"monthly_transcription_seconds": 7200, "storage_months": 3, "allowed_integrations": []}', true, now()),
        ('plan_pro', 'pro', 900, 9000, '{"monthly_transcription_seconds": 72000, "storage_months": 12, "allowed_integrations": ["notion", "google_calendar"]}', true, now()),
        ('plan_premium', 'premium', 2900, 29000, '{"monthly_transcription_seconds": 1000000000, "storage_months": 1000, "allowed_integrations": ["notion", "google_calendar", "zapier"]}', true, now())
        ON CONFLICT (name) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_embeddings')
    op.drop_table('admin_logs')
    op.drop_table('plans')
    # ### end Alembic commands ###
