"""add_push_subscriptions

Revision ID: e1484e7bfcb3
Revises: fe3748f4d730
Create Date: 2025-12-25 14:36:06.557333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1484e7bfcb3'
down_revision: Union[str, Sequence[str], None] = 'fe3748f4d730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('note_embeddings',
    # sa.Column('note_id', sa.String(), nullable=False),
    # sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    # sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    # sa.PrimaryKeyConstraint('note_id')
    # )
    op.add_column('notes', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('processing_step', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_onboarded', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('push_subscriptions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_subscriptions')
    op.drop_column('users', 'role')
    op.drop_column('users', 'has_onboarded')
    op.drop_column('notes', 'processing_step')
    op.drop_column('notes', 'storage_key')
    op.drop_table('note_embeddings')
    # ### end Alembic commands ###
