"""add_cancel_at_period_end

Revision ID: f829e123abc4
Revises: 4e75d8c50552
Create Date: 2023-10-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f829e123abc4'
down_revision = '4e75d8c50552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cancel_at_period_end')
    # ### end Alembic commands ###
