from .base import BaseIntegration
from app.models import Integration, Note
from evernote.api.client import EvernoteClient
from evernote.edam.type.ttypes import Note as EvernoteNote, Resource, Data, ResourceAttributes
from evernote.edam.notestore.ttypes import NoteFilter
import logging
import hashlib
import binascii

class EvernoteIntegration(BaseIntegration):
    async def sync(self, integration: Integration, note: Note):
        self.logger.info(f"Syncing note {note.id} to Evernote")

        # 1. Authenticate
        access_token = integration.auth_token
        if isinstance(access_token, dict):
            access_token = access_token.get("access_token") # Or developer token string
        
        if not access_token:
            raise ValueError("Evernote access token missing")
        
        # Determine sandbox/production (default to production for user apps)
        sandbox = (integration.settings or {}).get("sandbox", False)

        try:
            client = EvernoteClient(token=access_token, sandbox=sandbox)
            note_store = client.get_note_store()
            
            # 2. Prepare Content (ENML)
            # ENML is a subset of XHTML
            # We must escape special characters or wrap in CDATA (not really supported in ENML body directly without careful handling)
            # Simplest is to just use basic html tags.
            
            content_html = ""
            if note.summary:
                content_html += f"<h3>Summary</h3><p>{self._escape(note.summary)}</p>"
            
            if note.action_items:
                content_html += "<h3>Action Items</h3><ul>"
                for item in note.action_items:
                    content_html += f"<li><en-todo/>{self._escape(str(item))}</li>"
                content_html += "</ul>"
                
            if note.transcription_text:
                content_html += f"<h3>Transcript</h3><pre>{self._escape(note.transcription_text)}</pre>"
            
            # Wrap in ENML boilerplate
            enml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>
{content_html}
<p><i>Generated by VoiceBrain</i></p>
</en-note>"""

            # 3. Create Note Object
            en_note = EvernoteNote()
            en_note.title = note.title or "Untitled VoiceBrain Note"
            en_note.content = enml
            
            # Tags
            if note.tags:
                en_note.tagNames = note.tags
                
            # notebookGuid
            notebook_guid = (integration.settings or {}).get("notebook_guid")
            if notebook_guid:
                en_note.notebookGuid = notebook_guid
                
            # 4. Create Note on Server
            # NoteStore interactions are synchronous in evernote3 sdk
            created_note = note_store.createNote(en_note)
            self.logger.info(f"Successfully created Evernote note: {created_note.guid}")
            
        except Exception as e:
            self.logger.error(f"Evernote sync failed: {e}")
            raise e

    def _escape(self, text: str) -> str:
        """Escape XML special characters."""
        if not text: return ""
        return (text.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                    .replace('"', "&quot;")
                    .replace("'", "&apos;"))
